default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: angipl_development

test:
  <<: *default
  database: angipl_test

production:
  <<: *default
  database: angipl_production
  username: 
  password: 